Sticker Module
SpEcHiDe/PyroGramBot pull request #45
Opened 2021-07-10 18:49 UTC by bughunter0

2021-07-11 00:34 UTC, SpEcHiDe requested changes

2021-07-11 00:34 UTC, SpEcHiDe commented on pyrobot/plugins/stickers/findsticker.py
> +  except Exception as error:
🤔🤒

2021-07-11 00:34 UTC, SpEcHiDe commented on pyrobot/plugins/stickers/getstickers.py
> +                   except Exception as error:
😳😳

2021-07-13 16:35 UTC, bughunter0 reviewed
😕

2021-07-13 16:38 UTC, closed without merging